import TypeUser from "./TypeUser";
import TypeNft from "./TypeNFT";
export type NftWithUser = TypeNft & TypeUser;
export const liveAuction: NftWithUser[] = [
  {
    img: "./img/nft/liveAuction/1.png",
    title: "Hamlet Contemplates",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "Triumphant Awakening",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "Living Vase 01 by Lanza",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "Flame Dress' by Balmain",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "E ",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "F ",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "G ",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
  {
    img: "./img/nft/liveAuction/1.png",
    title: "H ",
    net: "BSC",
    userName: "SalvadorDali",
    userAvatar: "./img/user/1.png",
    userType: "Creator",
    price: 4.29,
  },
];
